name: Go
description: Validate and test Go code
runs:
  using: composite
  steps:
  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: 1.19
  - name: Build
    shell: bash
    run: go build -v ./...
  - name: Run unit tests
    shell: bash
    run: make test
